runtime: python37
env: standard

env_variables:
  UPLOAD_FOLDER: '/tmp'
  BUCKET: 'https://storage.googleapis.com/foodappproducts/'
  BUCKET_NAME: 'foodappproducts'
  MAIL_ACCOUNT: 'admin@onedaystory.co'
  MAIL_PASSWORD: 'Chipperfield01'
  DB_USER: 'root'
  DB_PASS: 'artapp01'
  NEXMO_API_SECRET: '2F0d2CE301A@6C7'
  NEXMO_API_KEY: 'ad2030ed'


handlers:
  - url: .*
    script: auto
    secure: always
    redirect_http_response_code: 301

entrypoint: gunicorn -b :$PORT foodapp:app



# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
